language: python
python:
  - "3.7"

install:
  - pip install -r requirements/test.txt

script: flake8 app/**/** tests/** && python -m pytest -W ignore -vv tests/* --cov=./app
after_success:
  - coveralls
